version: '3.8'

services:
  jm-monitor:
    container_name: jm-monitor
    # 使用你在 GitHub Secrets 里配置的最新专属 ACR 镜像地址
    image: crpi-framb20i8zwsu1xc.cn-hangzhou.personal.cr.aliyuncs.com/jm-lab/jm-monitor:latest
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - MONITOR_INTERVAL=15
      - LOG_PATH=/app/logs # ✨ 告诉 Python，把日志写到容器内部的 /app/logs 里
      - FEISHU_WEBHOOK_URL=${https://open.feishu.cn/open-apis/bot/v2/hook/e99f601a-3a5e-4360-b536-4949eac47a8a}

    # ✨【核心战役点】挂载持久化数据卷
    volumes:
      # 语法格式：宿主机(阿里云物理机)路径 : 容器内部路径
      - /app/jm-monitor/logs:/app/logs
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10000/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # ✨【今日新增】：完全独立的“商城订单微服务”
  order-service:
    image: nginx:alpine
    container_name: order-service
    restart: always
    # 💡 极其重要：注意看！这里我们故意【没有】写 ports 端口映射！
    # 因为它运行在 Docker 默认创建的同一个虚拟网桥里。
    # 外部网民无法通过任何端口访问这个 Nginx，但我们的雷达可以通过 http://order-service:80 畅行无阻地访问它！
    # 这就是微服务“内网绝对隔离”的安全设计。
