name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip3 install flask requests pytest #确保云端耶装上这些零件

    - name: Run tests
      run: |
        pytest # 执行你刚刚通过的那两个测试




