name: Terraform Alibaba Cloud Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Clean Lock File
        run: rm -f .terraform.lock.hcl

      - name: Terraform Init
        run: terraform init -upgrade
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
          ALICLOUD_REGION: "cn-hangzhou"

      - name: Terraform Plan
        run: terraform plan
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
          ALICLOUD_REGION: "cn-hangzhou"

      - name: Terraform Apply
        # 只有在 main 分支 push 时才真正执行修改
        run: terraform apply -auto-approve
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
          ALICLOUD_REGION: "cn-hangzhou"
